# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-13 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Category',
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.Category')),
            ],
            options={
                'db_table': 'Chemistry',
                'verbose_name': 'Chemistry',
                'verbose_name_plural': 'Chemistries',
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('renewal_date', models.DateTimeField(editable=False)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.Category')),
            ],
            options={
                'db_table': 'Documentation',
                'verbose_name': 'Documentation',
                'verbose_name_plural': 'Documentation',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DocumentType',
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Employee',
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('chemistry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.Chemistry')),
            ],
            options={
                'db_table': 'Test',
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.AddField(
            model_name='documentation',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.Employee'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='test_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.Test'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.DocumentType'),
        ),
    ]
