# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.Employee'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='renewal_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
