# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20171213_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='file_link',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='File Link'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Web Link'),
        ),
    ]
