# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-13 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20171213_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='file_path',
            field=models.TextField(blank=True, null=True, verbose_name='File Path (e.g. competencies)'),
        ),
    ]
