# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-15 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20171213_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Competency',
                'verbose_name': 'Competency',
                'verbose_name_plural': 'Competencies',
            },
        ),
        migrations.CreateModel(
            name='CompetencyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.TextField(verbose_name='File Path')),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('renewal_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('competency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.Competency')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.Employee')),
            ],
            options={
                'db_table': 'CompetencyDocument',
                'verbose_name': 'Competency Document',
                'verbose_name_plural': 'Competency Documents',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.Category')),
                ('test_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.Test')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.DocumentType')),
            ],
            options={
                'db_table': 'Document',
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='type_id',
        ),
        migrations.DeleteModel(
            name='Documentation',
        ),
    ]
